server:
  # Base-URL of LLM Server
  url: "https://134.130.13.43:4000/v1"
  client: "openai_sdk"
  # Enter model name to evaluate 
  model_name: "meta-llama/Meta-Llama-3.1-8B-Instruct"
  
  verify_ssl: false
  api_key_env: "MED_SERVER_API_KEY"
  api_key: ""
  timeout_s: 60

benchmark_settings:
  limit_samples: null # Whole dataset
  temperature: 0.0
  max_tokens: 256
  # optional: sleep between requests to avoid rate limits
  sleep_s: 0
  # optional: abort if too many errors
  max_errors: 200
